// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/alexzhaozzzz/gin_wire_layout/internal/model"
	"github.com/alexzhaozzzz/gin_wire_layout/internal/model/mysql"
	"github.com/alexzhaozzzz/gin_wire_layout/internal/repo"
	"github.com/alexzhaozzzz/gin_wire_layout/internal/router"
	"github.com/alexzhaozzzz/gin_wire_layout/internal/service"
	"github.com/alexzhaozzzz/gin_wire_layout/pkg/connect/mysqlx"
	"github.com/alexzhaozzzz/gin_wire_layout/pkg/serverx"
	"github.com/google/wire"
)

// Injectors from wire.go:

// initRouter 初始化router
func initRouter(ds mysqlx.IDataSource) serverx.IRouter {
	defaultMysqlDataSource := mysql.NewDefaultMysql()
	iUserRepo := model.NewUserImp(defaultMysqlDataSource)
	userService := service.NewUserService(iUserRepo)
	apiRouter := router.NewApiRouter(userService)
	return apiRouter
}

// wire.go:

var providerSet = wire.NewSet(model.ProviderSet, repo.ProviderSet, service.ProviderSet)
